<?php
use Ouzo\Config;

?>
<html>
<head>
    <title>Arduino Dartboard Panel</title>

    <?= addFile(['type' => 'link', 'params' => ['url' => '/public/css/bootstrap.min.css']]); ?>
    <?= addFile(['type' => 'link', 'params' => ['url' => '/public/css/bootstrap-theme.min.css']]); ?>
    <?= addFile(['type' => 'link', 'params' => ['url' => '/public/css/style.css']]); ?>

    <?= addFile(['type' => 'script', 'params' => ['url' => '/public/js/jquery-1.11.0.min.js']]); ?>
    <?= addFile(['type' => 'script', 'params' => ['url' => '/public/js/bootstrap.min.js']]); ?>

    <link href="<?= url('/public/images/icon.png') ?>" rel="shortcut icon">
</head>
<body>
<header>
</header>
<nav class="navbar navbar-custom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-nav"
                    aria-expanded="false">
                <span class="sr-only">MENU</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= indexGamesPath() ?>">
                <img src="<?= url('/public/images/thulium.png'); ?>" alt="Logo thulium.pl">
            </a>
        </div>

        <p class="navbar-right navbar-text">Arduino based dartboard game</p>
    </div>
</nav>

<section class="container main-container">
    <?= $this->layoutContent(); ?>
</section>


<footer>
    <div class="container">
        <div class="col-md-5 pull-left">
            <small>Copyright &copy; 2016
                <a href="http://ouzoframework.org" class="custom-link" target="_blank">Ouzo Developers</a>
            </small>
        </div>

        <div class="col-md-3 pull-right">
            <small>Sponsored by <a href="http://thulium.pl" class="custom-link" target="_blank">thulium.pl</a></small>
        </div>
    </div>
    <? if (Config::getValue('debug')): ?>
        <div class="container">
            <hr>
            <div class="col-md-12">
                <button onclick="clearErrors();" class="btn btn-default">Clear errors</button>
                <div id="error" class="error-container"></div>
            </div>
        </div>
        <script>
            var defaultErrorHandler = window.onerror;

            function logMessage(errorText, type) {
                type = type || 'error';
                errorText = "<div>" + type + ": " + errorText + "</div>";
                $('#error').append(errorText);
                try {
                    var item = localStorage.getItem('dartboard-error');
                    var savedError = item ? item : '';
                    localStorage.setItem('dartboard-error', savedError + errorText);
                } catch (e) {
                }
            }

            window.onerror = function (message, url, line, column, error) {
                var errorLine = '<div><span class="trace">' + url + ' line:' + line + ', col:' + column + '</span> msg: ' + message + '</div>';
                logMessage(errorLine);
                if (defaultErrorHandler) {
                    defaultErrorHandler.apply(window, arguments);
                }
                return false;
            };

            var errors = localStorage.getItem('dartboard-error');
            if (errors) {
                $('#error').html(errors);
            }

            function clearErrors() {
                localStorage.removeItem('dartboard-error');
                $('#error').html('');
            }
        </script>
    <? endif; ?>
</footer>

</body>
</html>
