<html>
<head>
    <title>Arduino Dartboard Panel</title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <?= addFile(['type' => 'link', 'params' => ['url' => '/public/css/style.css']]); ?>

    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<header>
</header>

<div class="content">
    <?php echo $this->layoutContent(); ?>
</div>
</body>
</html>
