<?
use Ouzo\Config;

?>

<style>
    th {
        text-align: center;
    }

    .bigger {
        font-size: 20pt;
    }
</style>

<div id="game_content">
</div>

<?= addFile(array('type' => 'script', 'params' => array('url' => '/public/js/long-poll.js'))); ?>

<script>
    $(function () {

        function loadGameContent() {
            $.get('<?= gameContentGamesPath() ?>', function (content) {
                $('#game_content').html(content);
            });
        }

        eventBus.bind('hit', function (event, hit) {
            playSoundsForHit(hit);
            loadGameContent();
        });

        eventBus.bind('refresh', function () {
            loadGameContent();
        });

        eventBus.bind('next_player', function () {
            playFilesSynchronously(['next']);
        });

        function playSoundsForHit(hit) {
            var files = [];
            if (hit.winner) {
                playFilesSynchronously(['winner']);
                return;
            }

            if (hit.scored) {
                if (hit.multiplier == 2) {
                    files.push('double');
                }

                if (hit.multiplier == 3) {
                    files.push('triple');
                    files.push('yeah');
                }

                if (hit.field == 25) {
                    files.push('bullseye');
                    if (hit.multiplier == 2) {
                        files.push('yeah');
                    }
                }
                if (files.length == 0) {
                    files.push('yes');
                }
            } else {
                files.push('no');
            }

            playFilesSynchronously(files);
        }

        function playFilesSynchronously(files) {
            if (files.length == 0) {
                return;
            }
            var currentPlayIndex = 0;

            function play() {
                var path = '<?= Config::getPrefixSystem() ?>' + '/public/sounds/' + files[currentPlayIndex] + '.mp3';
                var audio = new Audio(path);
                audio.onended = function () {
                    currentPlayIndex++;
                    if (currentPlayIndex < files.length) {
                        play();
                    }
                };
                audio.play();
            }

            play();
        }

        loadGameContent();
    });
</script>
