<?
use Ouzo\Config;

?>

<style>
    th {
        text-align: center;
    }

    .bigger {
        font-size: 20pt;
    }
</style>

<div class="col-md-6 col-md-offset-3">
    <?= postButton('New game', restartGamesPath()) ?>
    <?= postButton('Cancel game', cancelGamesPath()) ?>
    <?= postButton('Next player', nextPlayerGamesPath(), ['class' => 'pull-right', 'id' => 'next_player']) ?>
    <hr>
    <div id="game_content"></div>
</div>

<?= addFile(array('type' => 'script', 'params' => array('url' => '/public/js/long-poll.js'))); ?>

<script>
    $(function () {
        eventBus.bind('hit', function (event, hit) {
            playSoundsForHit(hit);
            loadGameContent();
        });

        eventBus.bind('refresh', function () {
            loadGameContent();
        });

        eventBus.bind('next_player', function () {
            playFilesSynchronously(['next']);
        });

        $("#next_player").submit(function (ev) {
            ev.preventDefault();
            $.post($(this).attr('action'));
        });

        function loadGameContent() {
            $.get('<?= gameContentGamesPath() ?>', function (content) {
                $('#game_content').html(content);
            });
        }

        function playSoundsForHit(hit) {
            var files = [];
            if (hit.scored) {
                if (hit.multiplier == 2) {
                    files.push('double');
                }

                if (hit.multiplier == 3) {
                    files.push('triple');
                    files.push('yeah');
                }

                if (hit.field == 25) {
                    files.push('bullseye');
                    files.push('yeah');
                }

                if (files.length == 0) {
                    files.push('yes');
                }

                if (hit.winner) {
                    files.push('winner');
                }
            } else {
                files.push('no');
            }

            if (!hit.winner && hit.shots_left == 0) {
                files.push('next');
            }

            playFilesSynchronously(files);
        }

        function playFilesSynchronously(files) {
            if (files.length == 0) {
                return;
            }
            var currentPlayIndex = 0;

            function play() {
                var path = '<?= Config::getPrefixSystem() ?>' + '/public/sounds/' + files[currentPlayIndex] + '.mp3';
                var audio = new Audio(path);
                audio.onended = function () {
                    currentPlayIndex++;
                    if (currentPlayIndex < files.length) {
                        play();
                    }
                };
                audio.play();
            }

            try {
                play();
            } catch (e) {
                logMessage(e.message);
            }
        }

        loadGameContent();
    });
</script>
