<?
use Application\Model\Hit;

?>
<div class="col-md-6 col-md-offset-3">
    <?= postButton('New game', restartGamesPath()) ?>
    <?= postButton('Cancel game', cancelGamesPath()) ?>
    <?= postButton('Next player', nextPlayerGamesPath(), ['class' => 'pull-right']) ?>

    <hr>
    <div class="bigger">
        <div>Round: <?= $this->game->round ?></div>
        <div>Current user: <?= $this->game->current_game_user->user->login ?></div>
        <div>Left: <?= $this->game->current_game_user->getLeftShoots() ?></div>

        <hr>

        <div>
            Players:
            <table class="table">
                <thead>
                <tr>
                    <td>Login</td>
                    <td>15</td>
                    <td>16</td>
                    <td>17</td>
                    <td>18</td>
                    <td>19</td>
                    <td>20</td>
                    <td>25</td>
                </tr>
                </thead>
                <? foreach ($this->game->game_users as $game_user): ?>
                    <tr>
                        <td><?= $game_user->user->login ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(15)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(16)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(17)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(18)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(19)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(20)) ?></td>
                        <td><?= str_repeat('X', $game_user->getScore(25)) ?></td>
                    </tr>
                <? endforeach; ?>
            </table>
        </div>
    </div>

    <div>
        Last hits:
        <? foreach (Hit::queryBuilder()->with('userGame->user')->order('id desc')->limit(9)->fetchAll() as $hit): ?>
            <div><?= $hit->userGame->user->login ?> <?= $hit->field ?>x<?= $hit->multiplier ?></div>
        <? endforeach; ?>
    </div>
</div>
