<?php
use Application\Model\Game;
use Ouzo\Utilities\Date;

/** @var Game[] $games */
$games = $this->games
?>
<?= showNotices(); ?>
<div class="panel panel-default">
    <div class="panel-heading">Games</div>
    <div class="panel-body">
        <?= linkButton(['name' => 'back', 'value' => 'Back', 'url' => indexHomePath(), 'class' => "btn btn-primary"]); ?>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Date</th>
                <th>Type</th>
                <th>Rounds</th>
                <th>Winner</th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($games as $game): ?>
                <tr>
                    <td><?= linkTo(Date::formatDateTime($game->started_at), showGamesPath($game->id)); ?></td>
                    <td><?= linkTo($game->type, showGamesPath($game->id)); ?></td>
                    <td><?= linkTo($game->round, showGamesPath($game->id)); ?></td>
                    <td><?= linkTo($game->winner_game_user->user->login, playerPath($game->winner_game_user->user->id)); ?></td>
                </tr>
            <? endforeach ?>
            </tbody>
        </table>
    </div>
</div>