<?php
use Application\Model\Engines\GameEngineStrategyMapper;
use Application\Model\Game;

/** @var Game $game */
$game = $this->game;
?>
<div class="col-md-4 col-md-offset-4 text-center">
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            Start game <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <? foreach (GameEngineStrategyMapper::getTypeNames() as $type => $name): ?>
                <li><a href="<?= gameGamesPath() ?>?type=<?= $type ?>"><?= $name ?></a></li>
            <? endforeach; ?>
        </ul>
    </div>
    <?= linkButton(['name' => 'players', 'value' => 'Players', 'url' => playersPath(), 'class' => "btn btn-primary"]); ?>

    <hr>

    <div>
        <? foreach ($game->possibleUsers() as $user): ?>
            <form action="<?= addPlayerGamesPath($user->id) ?>" class="add-player" method="post">
                <button type="submit" class="btn btn-primary">Add <?= $user->login ?></button>
            </form>
        <? endforeach; ?>
    </div>

    <div>
        Players:
        <table class="table">
            <thead>
            <tr>
                <td>Login</td>
            </tr>
            </thead>
            <? foreach ($game->game_users as $gameUser): ?>
                <tr>
                    <td><?= $gameUser->user->login ?></td>
                </tr>
            <? endforeach; ?>
        </table>
    </div>
</div>
