<?php
use Application\Model\GameFormObject;
use Application\Model\User;

/** @var GameFormObject $game */
$game = $this->game;
?>


<?= showErrors($this->game->getErrors()); ?>

<? $form = formFor($this->game); ?>
<?= $form->start(createGamesPath(), 'POST', array('class' => 'form-horizontal')); ?>



<div class="col-md-4 col-md-offset-4 text-center">
    <button type="submit" class="btn btn-primary">Start</button>
    <?= linkButton(array('name' => 'cancel', 'value' => 'Cancel', 'url' => indexGamesPath(), 'class' => "btn btn-default")); ?>
    <hr>

    <div >
        Type:

        <div >
            <?= $form->selectField('type', ['cricket' => 'cricket', '101' => '101']) ?>
        </div>
    </div>

    <div>
        Available Players:

        <div >
            <? foreach (User::all() as $user): ?>
                <button class="btn btn-primary add-user" data-id="<?= $user->id ?>" data-login="<?= $user->login ?>">Add <?= $user->login ?></button>
                <br/>
            <? endforeach; ?>
        </div>
    </div>
    <div>
        Selected Players:
        <div class="players">
        </div>
    </div>
</div>
<?php echo $form->end(); ?>

<script>
    $(function () {
        $('.add-user').click(function () {
            var login = $(this).data('login');
            var id = $(this).data('id');
            $('.players').append('<div class="player">' + login + '<input type="hidden" name="players[]" value="' + id + '"></div>');
            $(this).hide();
            return false;
        });
    });
</script>