<div class="col-md-4 col-md-offset-4 text-center">
    <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
            Start game <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
            <li><a href="<?= gameGamesPath() ?>?type=cricket">Cricket</a></li>
            <li><a href="<?= gameGamesPath() ?>?type=101">101</a></li>
        </ul>
    </div>
    <?= linkButton(['name' => 'players', 'value' => 'Players', 'url' => playersPath(), 'class' => "btn btn-primary"]); ?>

    <hr>

    <div>
        <? foreach ($this->game->possibleUsers() as $user): ?>
            <form action="<?= addPlayerGamesPath($user->id) ?>" class="add-player" method="post">
                <button type="submit" class="btn btn-primary">Add <?= $user->login ?></button>
            </form>
        <? endforeach; ?>
    </div>

    <div>
        Players:
        <table class="table">
            <thead>
            <tr>
                <td>Login</td>
            </tr>
            </thead>
            <? foreach ($this->game->game_users as $game_user): ?>
                <tr>
                    <td><?= $game_user->user->login ?></td>
                </tr>
            <? endforeach; ?>
        </table>
    </div>
</div>
