<style>
    .number {
        font-family: monospace;
        font-size: 15px;
        font-weight: bold;
        margin-bottom: 5px;
    }
</style>

Simulate hit: <br/>
<?

foreach (['s', 'd', 't'] as $multiplier) {
    echo "<br/>";
    foreach (range(1, 20) as $number) {
        echo <<<_IN
    <input type="button" class="number btn btn-primary" value="{$number}{$multiplier}">
_IN;
    }
}
?>
<br/>
<input type="button" class="number btn btn-primary" value="25s">
<input type="button" class="number btn btn-primary" value="25d">
<br/>

<script>
    $(function () {
        $('.number').click(function () {
            var value = $(this).val();
            $.post('<?= indexHitsPath()?>', {field: value});
        });
    });
</script>
