<?php
use Application\Model\Game;

/** @var Game $game */
$game = $this->game;
?>

<div>
    <table class="table score">
        <thead>
        <tr>
            <td style="width: 30%;">Player</td>
            <td style="width: 20%;">Score</td>
            <td>Best shots</td>
        </tr>
        </thead>
        <tbody>
        <? foreach ($game->game_users as $gameUser): ?>
            <tr>
                <td class="<?= $gameUser->isCurrent() ? 'current' : '' ?>"><?= $gameUser->user->login ?></td>
                <td class="text-center"><?= $gameUser->score ?></td>
                <td class="text-center">(<?= implode(' + ', $this->bestShots[$gameUser->getId()]) ?>)</td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
</div>
