<?php
use Application\Model\Game;

/** @var Game $game */
$game = $this->game;
?>

<div>
    <table class="table score">
        <thead>
        <tr>
            <td style="width: 30%;">Player</td>
            <td style="width: 20%;">Score</td>
            <td>Best shot</td>
        </tr>
        </thead>
        <tbody>
        <? foreach ($this->game->game_users as $game_user): ?>
            <tr>
                <td class="<?= $game_user->isCurrent() ? 'current' : '' ?>"><?= $game_user->user->login ?></td>
                <td class="text-center"><?= $game_user->score ?></td>
                <td class="text-center"></td>
            </tr>
        <? endforeach; ?>
        </tbody>
    </table>
</div>