<?
use Application\Model\GameUser;
use Ouzo\Utilities\Json;

?>

<?
$closedPerRound = FlotHelper::toFlotData($this->game->game_users, function(GameUser $game_user) {
    return $game_user->getClosedByRoundForCricket();
});
?>

<style>
    .chart-placeholder
    {
        height: 300px;
    }

    .legendLabel {
        color: #A6A1FF !important;
    }

    #closed-per-round div.flot-text
    {
        color: #A6A1FF !important;
    }
</style>

<br/>
<br/>
Closed by round:
<div id="closed-per-round" class="chart-placeholder"></div>
<div id="closed-per-round-legend-container"></div>

<script type="text/javascript">

    $(function () {
        $.plot("#closed-per-round", <?= Json::encode($closedPerRound)?>, {
            legend: {
                container: $("#closed-per-round-legend-container"),
                show: true
            },
            xaxis: {
                ticks: 10,
                min: 1,
                tickDecimals: 0
            },
            yaxis: {
                ticks: 10,
                min: 0,
                max : 9,
                tickDecimals: 0
            }
        });
    });
</script>
