<?php
use Application\Model\Game;
use Ouzo\Config;

function score($score)
{
    return str_repeat('<div class="cricket-score open"></div>', 3 - $score) .
    str_repeat('<div class="cricket-score closed"></div>', $score);
}

/** @var Game $game */
$game = $this->game;
?>

<div>
    <table class="table score">
        <thead>
        <tr>
            <td>Player</td>
            <td>15</td>
            <td>16</td>
            <td>17</td>
            <td>18</td>
            <td>19</td>
            <td>20</td>
            <td>25</td>
        </tr>
        </thead>
        <? foreach ($game->game_users as $gameUser): ?>
            <tr>
                <td class="<?= $gameUser->isCurrent() ? 'current' : '' ?>"><?= $gameUser->user->login ?></td>
                <td><?= score($gameUser->getScore(15)) ?></td>
                <td><?= score($gameUser->getScore(16)) ?></td>
                <td><?= score($gameUser->getScore(17)) ?></td>
                <td><?= score($gameUser->getScore(18)) ?></td>
                <td><?= score($gameUser->getScore(19)) ?></td>
                <td><?= score($gameUser->getScore(20)) ?></td>
                <td><?= score($gameUser->getScore(25)) ?></td>
            </tr>
        <? endforeach; ?>
    </table>
</div>
