<?php
use Application\Model\Game;
use Application\Model\GameUser;
use Ouzo\Config;
use Ouzo\Utilities\Json;

function score($score)
{
    return str_repeat('<div class="cricket-score open"></div>', 3 - $score) .
    str_repeat('<div class="cricket-score closed"></div>', $score);
}

/** @var Game $game */
$game = $this->game;
?>
<style>
    .chart-placeholder
    {
        height: 300px;
    }

    .legendLabel {
        color: #A6A1FF !important;
    }

    #progress-per-round div.flot-text
    {
        color: #A6A1FF !important;
    }
</style>

<div class="col-md-6 col-md-offset-3">
    <table class="table score">
        <thead>
        <tr>
            <td>Player</td>
            <td>15</td>
            <td>16</td>
            <td>17</td>
            <td>18</td>
            <td>19</td>
            <td>20</td>
            <td>25</td>
        </tr>
        </thead>
        <? foreach ($game->game_users as $gameUser): ?>
            <tr>
                <td class="<?= $gameUser->isCurrent() ? 'current' : '' ?>"><?= $gameUser->user->login ?></td>
                <td><?= score($gameUser->getScore(15)) ?></td>
                <td><?= score($gameUser->getScore(16)) ?></td>
                <td><?= score($gameUser->getScore(17)) ?></td>
                <td><?= score($gameUser->getScore(18)) ?></td>
                <td><?= score($gameUser->getScore(19)) ?></td>
                <td><?= score($gameUser->getScore(20)) ?></td>
                <td><?= score($gameUser->getScore(25)) ?></td>
            </tr>
        <? endforeach; ?>
    </table>


    Progress by round:
    <div id="progress-per-round" class="chart-placeholder"></div>
    <div id="progress-per-round-legend-container"></div>

</div>

<?
$progressPerRound = FlotHelper::toFlotData($this->game->game_users, function(GameUser $game_user) {
    return $game_user->getProgressByRoundForCricket();
});
?>
<script type="text/javascript">
    $(function () {
        $.plot("#progress-per-round", <?= Json::encode($progressPerRound)?>, {
            legend: {
                container: $("#progress-per-round-legend-container"),
                show: true
            },
            xaxis: {
                ticks: 10,
                min: 1,
                tickDecimals: 0
            },
            yaxis: {
                ticks: 10,
                min: 0,
                max : 100,
                tickDecimals: 0
            }
        });
    });
</script>
