<?= showNotices(); ?>

<div class="panel panel-default">
    <div class="panel-heading">Players</div>
    <div class="panel-body">
        <?= linkButton(['name' => 'add_new', 'value' => 'Add', 'url' => freshPlayerPath(), 'class' => "btn btn-primary"]); ?>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>#</th>
                <th>Player name</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->users as $index => $user): ?>
                <tr>
                    <td><?= linkTo($index, playerPath($user->id)); ?></td>
                    <td><?= linkTo($user->login, playerPath($user->id)); ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    </div>
</div>

